In [1]:
import cv2 
import glob
import numpy as np
import pandas as pd
import random
random.seed(10)
from scipy import stats
import sklearn.metrics as metrics
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)

In [2]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [3]:
#Read the Train folder of images
train_img = []
for img in glob.glob("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 2/Assignment 2 Dataset/Train/*.jpg"):
    n= cv2.imread(img)
    train_img.append(n)

In [4]:
#Convert the 2d image to 1d vector
train_array = []
train_all_arrays = []
for i in range(len(train_img)):
    train_array = train_img[i].flatten()
    train_all_arrays.append(train_array)
    train_array = []

In [5]:
#Put the Train in dataframe
train_df = pd.DataFrame(train_all_arrays)

In [6]:
#Read the text file
train_fileObject = open("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 2/Assignment 2 Dataset/Train/Training Labels.txt", "r")
train_data = train_fileObject.read().splitlines()

In [7]:
#Add the Label to the dataframe
train_df['Label'] = train_data

In [8]:
#Read the Test folder of images
test_img = []
for img in glob.glob("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 2/Assignment 2 Dataset/Test/*.jpg"):
    n= cv2.imread(img)
    test_img.append(n) 

In [9]:
#Convert the 2d image to 1d vector
test_array = []
test_all_arrays = []
for i in range(len(test_img)):
    test_array = test_img[i].flatten()
    test_all_arrays.append(test_array)
    test_array = []     

In [10]:
#Put the Test in dataframe
test_df = pd.DataFrame(test_all_arrays)

In [11]:
#Read the text file
test_fileObject = open("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 2/Assignment 2 Dataset/Test/Test Labels.txt", "r")
test_data = test_fileObject.read().splitlines()

In [12]:
#Add the Label to the dataframe
test_df['Label'] = test_data

In [13]:
#clf[2].predict_proba(x_test)
test_df

0  1  2  3  4  5  6  7  8  9  ...  2343  2344  2345  2346  2347  2348  \
0    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
1    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
3    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
4    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
..  .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   ...   ...   
195  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
196  9  9  9  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
197  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
198  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
199  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   

     2349  2350  2351  Label  
0       0     0     0      0  
1       0     0     0      0  
2       0     0     0      0  
3       0     0     0      0  
4       0     0     0      0  
..    ...   ...   ...    ...  
195     0     0     0      9  
196     0     0     0      9  
197     0     0     0      9  
198     0     0     0      9  
199     0     0     0      9  

[200 rows x 2353 columns]

In [14]:
def random_forest(number_of_sample, number_of_trees, maxDepth):
    A = train_df.sample(number_of_sample)
    x_train = A.copy()
    x_test = test_df.copy()
    y_train = A['Label']
    y_test = test_df['Label']
    clf=[]
    predictions = []
    mode=[]
    for i in range(number_of_trees):
        z = DecisionTreeClassifier(random_state = 10, max_depth = maxDepth)
        clf.append(z)
        z = z.fit(x_train, y_train)
    for i in range(number_of_trees):
        predictions.append(clf[i].predict(x_test))
    for i in range(number_of_trees):
        mode.append(stats.mode(predictions[i]))
    for i in range(number_of_trees):    
        print("Confusion:",confusion_matrix(y_test, predictions[i]))
        print("Accuracy:",metrics.accuracy_score(y_test, predictions[i]))    
    return mode    
random_forest(50, 10, 10)

Confusion: [[ 3  6  0 11  0  0  0  0  0  0]
 [ 0  3  2 15  0  0  0  0  0  0]
 [10  2  0  8  0  0  0  0  0  0]
 [15  0  1  4  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 16  4  0  0  0]
 [ 0  0  0  0  0 17  3  0  0  0]
 [ 0  0  0  0  0  0  0  5 13  2]
 [ 0  0  0  0  0  0  0  7  9  4]
 [ 0  0  0  0  0  0  0  8  9  3]]
Accuracy: 0.33
Confusion: [[ 3  6  0 11  0  0  0  0  0  0]
 [ 0  3  2 15  0  0  0  0  0  0]
 [10  2  0  8  0  0  0  0  0  0]
 [15  0  1  4  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 16  4  0  0  0]
 [ 0  0  0  0  0 17  3  0  0  0]
 [ 0  0  0  0  0  0  0  5 13  2]
 [ 0  0  0  0  0  0  0  7  9  4]
 [ 0  0  0  0  0  0  0  8  9  3]]
Accuracy: 0.33
Confusion: [[ 3  6  0 11  0  0  0  0  0  0]
 [ 0  3  2 15  0  0  0  0  0  0]
 [10  2  0  8  0  0  0  0  0  0]
 [15  0  1  4  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 16  4  0  0  0]
 [ 0  0  0  0  0 17  3  0  0  0]
 [ 0  0  0  0  0  0  0  5 13  2]
 [ 0  0  0 

[ModeResult(mode=array(['3'], dtype=object), count=array([38])),
 ModeResult(mode=array(['3'], dtype=object), count=array([38])),
 ModeResult(mode=array(['3'], dtype=object), count=array([38])),
 ModeResult(mode=array(['3'], dtype=object), count=array([38])),
 ModeResult(mode=array(['3'], dtype=object), count=array([38])),
 ModeResult(mode=array(['3'], dtype=object), count=array([38])),
 ModeResult(mode=array(['3'], dtype=object), count=array([38])),
 ModeResult(mode=array(['3'], dtype=object), count=array([38])),
 ModeResult(mode=array(['3'], dtype=object), count=array([38])),
 ModeResult(mode=array(['3'], dtype=object), count=array([38]))]

In [15]:
random_forest(50, 100, 10)

Confusion: [[ 1  7  1 11  0  0  0  0  0  0]
 [ 2  3  4 11  0  0  0  0  0  0]
 [ 2  5  1 12  0  0  0  0  0  0]
 [ 1  4  2 13  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 11  4  0  0]
 [ 0  0  0  0  0  0  9 11  0  0]
 [ 0  0  0  0  0  4  5 11  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 0.515
Confusion: [[ 1  7  1 11  0  0  0  0  0  0]
 [ 2  3  4 11  0  0  0  0  0  0]
 [ 2  5  1 12  0  0  0  0  0  0]
 [ 1  4  2 13  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 11  4  0  0]
 [ 0  0  0  0  0  0  9 11  0  0]
 [ 0  0  0  0  0  4  5 11  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 0.515
Confusion: [[ 1  7  1 11  0  0  0  0  0  0]
 [ 2  3  4 11  0  0  0  0  0  0]
 [ 2  5  1 12  0  0  0  0  0  0]
 [ 1  4  2 13  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 11  4  0  0]
 [ 0  0  0  0  0  0  9 11  0  0]
 [ 0  0  0  0  0  4  5 11  0  0]
 [ 0  0  

Confusion: [[ 1  7  1 11  0  0  0  0  0  0]
 [ 2  3  4 11  0  0  0  0  0  0]
 [ 2  5  1 12  0  0  0  0  0  0]
 [ 1  4  2 13  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 11  4  0  0]
 [ 0  0  0  0  0  0  9 11  0  0]
 [ 0  0  0  0  0  4  5 11  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 0.515
Confusion: [[ 1  7  1 11  0  0  0  0  0  0]
 [ 2  3  4 11  0  0  0  0  0  0]
 [ 2  5  1 12  0  0  0  0  0  0]
 [ 1  4  2 13  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 11  4  0  0]
 [ 0  0  0  0  0  0  9 11  0  0]
 [ 0  0  0  0  0  4  5 11  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 0.515
Confusion: [[ 1  7  1 11  0  0  0  0  0  0]
 [ 2  3  4 11  0  0  0  0  0  0]
 [ 2  5  1 12  0  0  0  0  0  0]
 [ 1  4  2 13  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 11  4  0  0]
 [ 0  0  0  0  0  0  9 11  0  0]
 [ 0  0  0  0  0  4  5 11  0  0]
 [ 0  0  

[ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['3'], dtype=object), count=array([47])),
 ModeResult(mode=array(['

In [16]:
random_forest(500, 100, 10)

Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 1.0
Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 1.0
Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0

Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 1.0
Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 1.0
Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0

[ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['

In [17]:
random_forest(1000, 100, 100)

Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 1.0
Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 1.0
Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0

Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 1.0
Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Accuracy: 1.0
Confusion: [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0

[ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['

In [47]:
#train_feature_names = A.columns

In [16]:
"""
from sklearn import tree
from matplotlib import pyplot as plt
for i in range(10):
    fig = plt.figure(figsize = (25,20))
    _ = tree.plot_tree(clf[i], feature_names = train_feature_names, filled = True, fontsize = 12)
"""

'\nfrom sklearn import tree\nfrom matplotlib import pyplot as plt\nfor i in range(10):\n    fig = plt.figure(figsize = (25,20))\n    _ = tree.plot_tree(clf[i], feature_names = train_feature_names, filled = True, fontsize = 12)\n'