In [39]:
import cv2 
import glob
import numpy as np
import pandas as pd
import random
random.seed(10)
from scipy import stats
import sklearn.metrics as metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [16]:
tr_img = []
for img in glob.glob("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 2/Assignment 2 Dataset/Train/*.jpg"):
    n= cv2.imread(img)
    tr_img.append(n)
tr_img  

[array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 

In [17]:
te_img = []
for img in glob.glob("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 2/Assignment 2 Dataset/Test/*.jpg"):
    n= cv2.imread(img)
    te_img.append(n) 
te_img    

[array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 

In [20]:
tr_text = open("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 2/Assignment 2 Dataset/Train/Training Labels.txt", "r")
tr_data = tr_text.read().splitlines()
tr_data

['0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0'

In [21]:
te_text = open("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 2/Assignment 2 Dataset/Test/Test Labels.txt", "r")
te_data = te_text.read().splitlines()
te_data

['0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8'

In [22]:
tr_1d = []
tr_arr = []
for i in range(2400):
    tr_arr = tr_img[i].flatten()
    tr_1d.append(tr_arr)
    tr_arr = []
tr_1d    

[array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([9, 9, 9, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dt

In [23]:
te_1d = []
te_arr = []
for i in range(200):
    te_arr = te_img[i].flatten()
    te_1d.append(te_arr)
    te_arr = []  
te_1d    

[array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([8, 8, 8, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([4, 4, 4, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dt

In [25]:
tr_df = pd.DataFrame(tr_1d)

In [26]:
tr_df['Numbers'] = tr_data

In [27]:
tr_df

0  1  2  3  4  5  6  7  8  9  ...  2343  2344  2345  2346  2347  2348  \
0     0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
1     0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2     0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
3     0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
4     0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
...  .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   ...   ...   
2395  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2396  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2397  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2398  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2399  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   

      2349  2350  2351  Numbers  
0        0     0     0        0  
1        0     0     0        0  
2        0     0     0        0  
3        0     0     0        0  
4        0     0     0        0  
...    ...   ...   ...      ...  
2395     0     0     0        9  
2396     0     0     0        9  
2397     0     0     0        9  
2398     0     0     0        9  
2399     0     0     0        9  

[2400 rows x 2353 columns]

In [28]:
te_df = pd.DataFrame(te_1d)

In [29]:
te_df['Numbers'] = te_data

In [30]:
te_df

0  1  2  3  4  5  6  7  8  9  ...  2343  2344  2345  2346  2347  2348  \
0    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
1    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
3    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
4    0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
..  .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   ...   ...   
195  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
196  9  9  9  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
197  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
198  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
199  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   

     2349  2350  2351  Numbers  
0       0     0     0        0  
1       0     0     0        0  
2       0     0     0        0  
3       0     0     0        0  
4       0     0     0        0  
..    ...   ...   ...      ...  
195     0     0     0        9  
196     0     0     0        9  
197     0     0     0        9  
198     0     0     0        9  
199     0     0     0        9  

[200 rows x 2353 columns]

In [32]:
sample = tr_df.sample(50)

In [44]:
x_tr = sample.copy()
x_te = te_df.copy()
y_tr = sample['Numbers']
y_te = te_df['Numbers']
tree=[]
for i in range(10):
        x = DecisionTreeClassifier(random_state = 10, max_depth = 10)
        tree.append(x)
        x = x.fit(x_tr, y_tr)
tree        

[DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10)]

In [43]:
predictions = []
for i in range(10):
    predictions.append(tree[i].predict(x_te))
predictions

[array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '1', '1', '1',
        '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
        '1', '2', '3', '3', '3', '3', '3', '3', '2', '3', '2', '3', '2',
        '2', '3', '3', '3', '2', '2', '3', '2', '3', '3', '3', '2', '2',
        '3', '3', '2', '2', '3', '3', '3', '3', '3', '2', '2', '2', '3',
        '2', '2', '6', '6', '5', '5', '4', '5', '4', '4', '4', '6', '4',
        '4', '4', '6', '5', '4', '4', '4', '4', '6', '5', '5', '5', '5',
        '5', '5', '6', '4', '4', '6', '5', '6', '5', '5', '5', '5', '5',
        '5', '5', '4', '5', '5', '5', '5', '5', '6', '4', '6', '5', '5',
        '5', '5', '5', '5', '4', '5', '6', '6', '5', '6', '7', '7', '7',
        '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7',
        '7', '7', '7', '7', '8', '8', '8', '8', '8', '8', '8', '8', '8',
        '8', '8', '8', '8', '8', '8', '8', '8', '8'

In [42]:
mode=[]
for i in range(10):
    mode.append(stats.mode(predictions[i]))
mode    

[ModeResult(mode=array(['5'], dtype=object), count=array([31])),
 ModeResult(mode=array(['5'], dtype=object), count=array([31])),
 ModeResult(mode=array(['5'], dtype=object), count=array([31])),
 ModeResult(mode=array(['5'], dtype=object), count=array([31])),
 ModeResult(mode=array(['5'], dtype=object), count=array([31])),
 ModeResult(mode=array(['5'], dtype=object), count=array([31])),
 ModeResult(mode=array(['5'], dtype=object), count=array([31])),
 ModeResult(mode=array(['5'], dtype=object), count=array([31])),
 ModeResult(mode=array(['5'], dtype=object), count=array([31])),
 ModeResult(mode=array(['5'], dtype=object), count=array([31]))]

In [41]:
for i in range(10):    
    print(confusion_matrix(y_te, predictions[i]))
    print(metrics.accuracy_score(y_te, predictions[i]))

[[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0  8 12  0  0  0  0  0  0]
 [ 0  0  9 11  0  0  0  0  0  0]
 [ 0  0  0  0 11  4  5  0  0  0]
 [ 0  0  0  0  3 14  3  0  0  0]
 [ 0  0  0  0  2 13  5  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
0.745
[[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0  8 12  0  0  0  0  0  0]
 [ 0  0  9 11  0  0  0  0  0  0]
 [ 0  0  0  0 11  4  5  0  0  0]
 [ 0  0  0  0  3 14  3  0  0  0]
 [ 0  0  0  0  2 13  5  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
0.745
[[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0  8 12  0  0  0  0  0  0]
 [ 0  0  9 11  0  0  0  0  0  0]
 [ 0  0  0  0 11  4  5  0  0  0]
 [ 0  0  0  0  3 14  3  0  0  0]
 [ 0  0  0  0  2 13  5  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 

In [ ]:
#second tree

In [45]:
sample = tr_df.sample(50)

In [46]:
x_tr = sample.copy()
x_te = te_df.copy()
y_tr = sample['Numbers']
y_te = te_df['Numbers']
tree=[]
for i in range(100):
        x = DecisionTreeClassifier(random_state = 10, max_depth = 10)
        tree.append(x)
        x = x.fit(x_tr, y_tr)
tree        

[DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_sta

In [47]:
predictions = []
for i in range(100):
    predictions.append(tree[i].predict(x_te))
predictions

[array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '2', '2', '2', '2', '2', '2',
        '2', '2', '2', '2', '1', '1', '2', '2', '1', '2', '2', '2', '2',
        '2', '2', '2', '1', '2', '2', '2', '2', '2', '1', '2', '1', '2',
        '2', '2', '2', '2', '2', '2', '2', '2', '3', '3', '3', '3', '3',
        '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3',
        '3', '3', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
        '4', '4', '4', '4', '4', '4', '4', '4', '4', '5', '6', '6', '6',
        '6', '6', '6', '6', '5', '5', '6', '6', '6', '5', '6', '6', '6',
        '6', '6', '5', '6', '6', '5', '6', '6', '6', '6', '6', '6', '6',
        '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '7', '7', '7',
        '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7',
        '7', '7', '7', '7', '8', '9', '9', '9', '9', '8', '9', '8', '9',
        '8', '8', '8', '9', '9', '8', '9', '9', '9'

In [48]:
mode=[]
for i in range(100):
    mode.append(stats.mode(predictions[i]))
mode    

[ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['2'], dtype=object), count=array([34])),
 ModeResult(mode=array(['

In [49]:
for i in range(100):    
    print(confusion_matrix(y_te, predictions[i]))
    print(metrics.accuracy_score(y_te, predictions[i]))

[[20  0  0  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 15  0  0  0]
 [ 0  0  0  0  0  1 19  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  9 11]
 [ 0  0  0  0  0  0  0  0 14  6]]
0.695
[[20  0  0  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 15  0  0  0]
 [ 0  0  0  0  0  1 19  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  9 11]
 [ 0  0  0  0  0  0  0  0 14  6]]
0.695
[[20  0  0  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 15  0  0  0]
 [ 0  0  0  0  0  1 19  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  9 11]
 [ 0  0  0  0  0  0  0  0 14 

[[20  0  0  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 15  0  0  0]
 [ 0  0  0  0  0  1 19  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  9 11]
 [ 0  0  0  0  0  0  0  0 14  6]]
0.695
[[20  0  0  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 15  0  0  0]
 [ 0  0  0  0  0  1 19  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  9 11]
 [ 0  0  0  0  0  0  0  0 14  6]]
0.695
[[20  0  0  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 15  0  0  0]
 [ 0  0  0  0  0  1 19  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  9 11]
 [ 0  0  0  0  0  0  0  0 14 

[[20  0  0  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 15  0  0  0]
 [ 0  0  0  0  0  1 19  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  9 11]
 [ 0  0  0  0  0  0  0  0 14  6]]
0.695
[[20  0  0  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 15  0  0  0]
 [ 0  0  0  0  0  1 19  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  9 11]
 [ 0  0  0  0  0  0  0  0 14  6]]
0.695
[[20  0  0  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  3 17  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  5 15  0  0  0]
 [ 0  0  0  0  0  1 19  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  9 11]
 [ 0  0  0  0  0  0  0  0 14 

In [50]:
#third tree

In [51]:
sample = tr_df.sample(500)

In [52]:
x_tr = sample.copy()
x_te = te_df.copy()
y_tr = sample['Numbers']
y_te = te_df['Numbers']
tree=[]
for i in range(100):
        x = DecisionTreeClassifier(random_state = 10, max_depth = 10)
        tree.append(x)
        x = x.fit(x_tr, y_tr)
tree

[DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_state=10),
 DecisionTreeClassifier(max_depth=10, random_sta

In [53]:
predictions = []
for i in range(100):
    predictions.append(tree[i].predict(x_te))
predictions

[array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '1', '1', '1',
        '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
        '1', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2',
        '2', '2', '2', '2', '2', '2', '2', '2', '3', '3', '3', '3', '3',
        '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3',
        '3', '3', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
        '4', '4', '4', '4', '4', '4', '4', '4', '4', '5', '5', '5', '5',
        '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
        '5', '5', '5', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6',
        '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '7', '7', '7',
        '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7',
        '7', '7', '7', '7', '8', '8', '8', '8', '8', '8', '8', '8', '8',
        '8', '8', '8', '8', '8', '8', '8', '8', '8'

In [54]:
mode=[]
for i in range(100):
    mode.append(stats.mode(predictions[i]))
mode

[ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['

In [55]:
#fourth tree

In [56]:
sample = tr_df.sample(1000)

In [57]:
x_tr = sample.copy()
x_te = te_df.copy()
y_tr = sample['Numbers']
y_te = te_df['Numbers']
tree=[]
for i in range(100):
        x = DecisionTreeClassifier(random_state = 10, max_depth = 100)
        tree.append(x)
        x = x.fit(x_tr, y_tr)
tree

[DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_depth=100, random_state=10),
 DecisionTreeClassifier(max_dep

In [58]:
predictions = []
for i in range(100):
    predictions.append(tree[i].predict(x_te))
predictions

[array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '1', '1', '1',
        '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
        '1', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2',
        '2', '2', '2', '2', '2', '2', '2', '2', '3', '3', '3', '3', '3',
        '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3',
        '3', '3', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
        '4', '4', '4', '4', '4', '4', '4', '4', '4', '5', '5', '5', '5',
        '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5',
        '5', '5', '5', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6',
        '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '7', '7', '7',
        '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7', '7',
        '7', '7', '7', '7', '8', '8', '8', '8', '8', '8', '8', '8', '8',
        '8', '8', '8', '8', '8', '8', '8', '8', '8'

In [59]:
mode=[]
for i in range(100):
    mode.append(stats.mode(predictions[i]))
mode

[ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['0'], dtype=object), count=array([20])),
 ModeResult(mode=array(['