In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sympy import symbols, solve
test = pd.read_csv(r'C:\Users\Sharm\Desktop\ML\Test.csv')
train = pd.read_csv(r'C:\Users\Sharm\Desktop\ML\Train.csv')

In [2]:

z=train.drop(["Species"],axis=1)
mat=z.to_numpy()
x_tilda = np.concatenate((mat, np.ones((105,1))), axis=1)
target1=[]
c=train['Species'].values
for i in range (105):
    if (c[i]=='Iris-versicolor'):
        target1+=[1]
    else:
        target1+=[-1]
w1 = np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ target1

w1

array([ 0.57079356, -1.18057071, -1.0433656 ])

In [3]:
z=train.drop(["Species"],axis=1)
mat=z.to_numpy()
x_tilda = np.concatenate((mat, np.ones((105,1))), axis=1)

target2=[]
c=train['Species'].values
for i in range (105):
    if (c[i]=='Iris-setosa'):
        target2+=[1]
    else:
        target2+=[-1]
w2= np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ target2

w2

array([-0.50070391,  0.03941776,  1.48011265])

In [4]:
z=train.drop(["Species"],axis=1)
mat=z.to_numpy()
x_tilda = np.concatenate((mat, np.ones((105,1))), axis=1)
target3=[]
c=train['Species'].values
for i in range (105):
    if (c[i]=='Iris-virginica'):
        target3+=[1]
    else:
        target3+=[-1]
w3= np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ target3

w3

array([-0.07008965,  1.14115295, -1.43674706])

In [5]:
test

PetalLengthCm  PetalWidthCm          Species
0             4.7           1.2  Iris-versicolor
1             1.7           0.3      Iris-setosa
2             6.9           2.3   Iris-virginica
3             4.5           1.5  Iris-versicolor
4             4.8           1.4  Iris-versicolor
5             1.5           0.4      Iris-setosa
6             3.6           1.3  Iris-versicolor
7             5.1           2.3   Iris-virginica
8             4.5           1.5  Iris-versicolor
9             3.9           1.2  Iris-versicolor
10            5.1           2.0   Iris-virginica
11            1.4           0.1      Iris-setosa
12            1.3           0.2      Iris-setosa
13            1.5           0.1      Iris-setosa
14            1.5           0.3      Iris-setosa
15            4.7           1.6  Iris-versicolor
16            5.8           2.2   Iris-virginica
17            3.9           1.1  Iris-versicolor
18            4.5           1.3  Iris-versicolor
19            5.6           2.2   Iris-virginica
20            1.6           0.2      Iris-setosa
21            4.9           1.8   Iris-virginica
22            1.6           0.4      Iris-setosa
23            5.6           2.1   Iris-virginica
24            6.4           2.0   Iris-virginica
25            5.2           2.3   Iris-virginica
26            5.8           1.8   Iris-virginica
27            5.9           2.3   Iris-virginica
28            1.4           0.3      Iris-setosa
29            1.6           0.2      Iris-setosa
30            1.0           0.2      Iris-setosa
31            1.5           0.4      Iris-setosa
32            4.4           1.4  Iris-versicolor
33            1.6           0.2      Iris-setosa
34            1.3           0.2      Iris-setosa
35            5.0           1.9   Iris-virginica
36            4.5           1.5  Iris-versicolor
37            1.5           0.2      Iris-setosa
38            1.4           0.2      Iris-setosa
39            1.5           0.1      Iris-setosa
40            5.1           1.9   Iris-virginica
41            4.5           1.6  Iris-versicolor
42            4.7           1.5  Iris-versicolor
43            1.3           0.4      Iris-setosa
44            1.5           0.2      Iris-setosa

In [6]:
array=np.empty(45,dtype=object)
for i in range(45):
    
    val1=test['PetalLengthCm'].values[i]
    val2=test['PetalWidthCm'].values[i]
    equ1=w1[0]*val1+w1[1]*val2+w1[2]
    equ2=w2[0]*val1+w2[1]*val2+w2[2]
    equ3=w3[0]*val1+w3[1]*val2+w3[2]
    if (equ1>equ2) : 
        if (equ1>equ3):
            array[i]='Iris-versicolor'
        else :
             array[i]='Iris-virginica'
    else : 
        if(equ2>equ3):
            array[i]='Iris-setosa'
        else:
             array[i]='Iris-virginica'
            
        
array


array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [7]:
count=0

for j in range(45):
    if(test['Species'].values[j]==array[j]):
        count+=1
    
acc=count/45*100
acc


82.22222222222221

In [8]:
test['Species']=test['Species'].replace(['Iris-versicolor'],'0')
test['Species']=test['Species'].replace(['Iris-setosa'],'1')
test['Species']=test['Species'].replace(['Iris-virginica'],'2')

x=test['Species']


matr=x.to_numpy()
matr

array(['0', '1', '2', '0', '0', '1', '0', '2', '0', '0', '2', '1', '1',
       '1', '1', '0', '2', '0', '0', '2', '1', '2', '1', '2', '2', '2',
       '2', '2', '1', '1', '1', '1', '0', '1', '1', '2', '0', '1', '1',
       '1', '2', '0', '0', '1', '1'], dtype=object)

In [9]:
y=np.empty(45,dtype='int')
for k in range (0,45):
    if(array[k]=='Iris-versicolor'):
        y[k]=0
    if(array[k]=='Iris-setosa'):
        y[k]=1
    if(array[k]=='Iris-virginica'):
        y[k]=2

y

array([0, 1, 2, 2, 0, 1, 2, 2, 2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1,
       1])

In [10]:

def conf_mat (a,b):
    correct =[0,0,0]
    for i in range (len(a)):
        if(a[i]==0):
            correct[0] +=1
        elif(a[i]==1):
            correct[1] +=1
        elif(a[i]==2):
            correct[2] +=1
        
    
    confusion_mat = pd.crosstab(a, b, rownames=['Actual'], colnames=['Predicted'], margins=True)

    print(confusion_mat)
    
    
            
conf_mat(x,y)

Predicted  0   1   2  All
Actual                   
0          5   0   8   13
1          0  19   0   19
2          0   0  13   13
All        5  19  21   45
