In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [1]:
import tensorflow as tf
import cv2 
import glob
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
from PIL import Image
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import os
os.environ['PYTHONHASHSEED'] = '0'
np.random.seed(37)
tf.random.set_seed(89)

In [2]:
#Read the train folder
from skimage.io import imread_collection
train_img = np.array(imread_collection(r'D:/computer science GIU/semester 6/Advanced Machine Learning/ass 3/Assignment 3 Dataset/Assignment 3 Dataset/Train/*.jpg'))

In [3]:
#Convert the 2d image to 1d vector
train_array = np.tile(0, (2400, 784))
for i in range(len(train_img)):
    train_array[i] = train_img[i].flatten()

In [4]:
#Read the text file in the train folder
train_fileObject = open("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 3/Assignment 3 Dataset/Assignment 3 Dataset/Train/Training Labels.txt", "r")
train_data = train_fileObject.read().splitlines()
train_data = [int(numeric_string) for numeric_string in train_data]

In [5]:
#Read the Test folder of images
test_img = np.array(imread_collection(r'D:/computer science GIU/semester 6/Advanced Machine Learning/ass 3/Assignment 3 Dataset/Assignment 3 Dataset/Test/*.jpg'))

In [6]:
#Convert the 2d image to 1d vector
test_array = np.tile(0, (200, 784))
for i in range(len(test_img)):
    test_array[i] = test_img[i].flatten()

In [7]:
#Read the text file in the test folder
test_fileObject = open("D:/computer science GIU/semester 6/Advanced Machine Learning/ass 3/Assignment 3 Dataset/Assignment 3 Dataset/Test/Test Labels.txt", "r")
test_data = test_fileObject.read().splitlines()
test_data = [int(numeric_string) for numeric_string in test_data]

In [8]:
#make new labels of 0 and 1 for the train data
train = []
for i in range(10):
    rows, cols = (240,10)
    arr = [[0]*cols]*rows
    arr[0][i] = 1
    for row in arr:
        train.append(row)

In [9]:
#make new labels of 0 and 1 for the test data
test = []
for i in range(10):
    rows, cols = (20,10)
    arr = [[0]*cols]*rows
    arr[0][i] = 1
    for row in arr:
        test.append(row)

In [10]:
#clasify the data
X_train = tf.constant(train_array, dtype=tf.float32)
Y_train = tf.constant(train, dtype=tf.float32)
X_test = tf.constant(test_array, dtype=tf.float32)
Y_test = tf.constant(test, dtype=tf.float32)

In [11]:
#Standardize the data
scaler = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_Y_train = scaler.fit_transform(Y_train)
scaled_X_test = scaler.fit_transform(X_test)
scaled_Y_test = scaler.fit_transform(Y_test)

In [41]:
#one layer standardized neural network
def Standardize_oneLayer(num_of_neurons, learning_rate_i, Epochs):
    model = keras.Sequential()
    # Add our layers
    model.add(layers.Dense(
        num_of_neurons, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))

    model.add(layers.Dense(
        10, # Amount of Neurons. We want one output
        activation='sigmoid' # Use sigmoid because we want to output a binary classification
    ))

    keras.optimizers.SGD(
        learning_rate = learning_rate_i
    )
    
    model.compile(
        loss='mean_squared_error', # The loss function that is being minimized
        optimizer='adam', # Our optimization function
        metrics=['accuracy'] # Metrics are different values that you want the model to track while training
    )
    
    model.fit(
        scaled_X_train,
        scaled_Y_train,
        epochs=Epochs,  
    )
    
    model.evaluate(
        scaled_X_test,
        scaled_Y_test
    )
    predict = model.predict(scaled_X_test)
    y_test_pred = [np.argmax(i) for i in predict]
    print(tf.math.confusion_matrix(labels = test_data, predictions = y_test_pred))
    print('Test Data accuracy: ', accuracy_score(test_data, y_test_pred)*100)

In [42]:
Standardize_oneLayer(500, 0.001, 100)

Epoch 1/100
75/75 [==============================] - 1s 7ms/step - loss: 0.6889 - accuracy: 0.7912
Epoch 2/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5533 - accuracy: 0.9433
Epoch 3/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5303 - accuracy: 0.9712
Epoch 4/100
75/75 [==============================] - 1s 10ms/step - loss: 0.5200 - accuracy: 0.9800
Epoch 5/100
75/75 [==============================] - 1s 13ms/step - loss: 0.5143 - accuracy: 0.9842
Epoch 6/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5107 - accuracy: 0.9879
Epoch 7/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5091 - accuracy: 0.9887
Epoch 8/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5078 - accuracy: 0.9908
Epoch 9/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5069 - accuracy: 0.9912
Epoch 10/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5065 - accuracy: 0.9912
Epoch 1

Epoch 83/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9921
Epoch 84/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9921
Epoch 85/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9921
Epoch 86/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9921
Epoch 87/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9925
Epoch 88/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9925
Epoch 89/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9929
Epoch 90/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9929
Epoch 91/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9929
Epoch 92/100
75/75 [==============================] - 1s 8ms/step - loss: 0.5049 - accuracy: 0.9929


In [43]:
Standardize_oneLayer(500, 0.001, 200)

Epoch 1/200
75/75 [==============================] - 1s 8ms/step - loss: 0.6805 - accuracy: 0.7942
Epoch 2/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5538 - accuracy: 0.9408
Epoch 3/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5301 - accuracy: 0.9692
Epoch 4/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5199 - accuracy: 0.9808
Epoch 5/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5137 - accuracy: 0.9850
Epoch 6/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5105 - accuracy: 0.9871
Epoch 7/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5090 - accuracy: 0.9871
Epoch 8/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5079 - accuracy: 0.9879
Epoch 9/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5071 - accuracy: 0.9887
Epoch 10/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5066 - accuracy: 0.9892
Epoch 11/

Epoch 83/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5055 - accuracy: 0.9912
Epoch 84/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5056 - accuracy: 0.9900
Epoch 85/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5060 - accuracy: 0.9896
Epoch 86/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5056 - accuracy: 0.9908
Epoch 87/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5051 - accuracy: 0.9904
Epoch 88/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5051 - accuracy: 0.9904
Epoch 89/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5050 - accuracy: 0.9904
Epoch 90/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5050 - accuracy: 0.9904
Epoch 91/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5050 - accuracy: 0.9904
Epoch 92/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5050 - accuracy: 0.9904


75/75 [==============================] - 1s 8ms/step - loss: 0.5050 - accuracy: 0.9908
Epoch 165/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5070 - accuracy: 0.9892
Epoch 166/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5325 - accuracy: 0.9558
Epoch 167/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5223 - accuracy: 0.9746
Epoch 168/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5149 - accuracy: 0.9842
Epoch 169/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5122 - accuracy: 0.9842
Epoch 170/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5109 - accuracy: 0.9858
Epoch 171/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5099 - accuracy: 0.9875
Epoch 172/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5094 - accuracy: 0.9883
Epoch 173/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5090 - accuracy: 0.9875
Epoc

In [20]:
#one layer not standardized neural network
def not_Standardize(num_of_neurons, learning_rate_i, Epochs):
    model = keras.Sequential()
    # Add our layers
    model.add(layers.Dense(
        num_of_neurons, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))

    model.add(layers.Dense(
        10, # Amount of Neurons. We want one output
        activation='sigmoid' # Use sigmoid because we want to output a binary classification
    ))

    keras.optimizers.SGD(
        learning_rate = learning_rate_i
    )
    
    model.compile(
        loss='mean_squared_error', # The loss function that is being minimized
        optimizer='adam', # Our optimization function
        metrics=['accuracy'] # Metrics are different values that you want the model to track while training
    )
    
    model.fit(
        X_train,
        Y_train,
        epochs=Epochs,  
    )
    
    model.evaluate(
        X_test,
        Y_test
    )
    predict = model.predict(X_test)
    y_test_pred = [np.argmax(i) for i in predict]
    print(tf.math.confusion_matrix(labels = test_data, predictions = y_test_pred))
    print('Test Data accuracy: ', accuracy_score(test_data, y_test_pred)*100)

In [21]:
not_Standardize(500, 0.001, 200)

Epoch 1/200
75/75 [==============================] - 2s 10ms/step - loss: 0.1295 - accuracy: 0.1067
Epoch 2/200
75/75 [==============================] - 1s 10ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 3/200
75/75 [==============================] - 1s 10ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 4/200
75/75 [==============================] - 1s 10ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 5/200
75/75 [==============================] - 1s 11ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 6/200
75/75 [==============================] - 1s 11ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 7/200
75/75 [==============================] - 1s 12ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 8/200
75/75 [==============================] - 1s 17ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 9/200
75/75 [==============================] - 2s 21ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 10/200
75/75 [==============================] - 1s 15ms/step - loss: 0.1000 - accuracy: 0.0988

75/75 [==============================] - 1s 12ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 83/200
75/75 [==============================] - 1s 11ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 84/200
75/75 [==============================] - 1s 10ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 85/200
75/75 [==============================] - 1s 10ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 86/200
75/75 [==============================] - 1s 11ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 87/200
75/75 [==============================] - 1s 9ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 88/200
75/75 [==============================] - 1s 8ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 89/200
75/75 [==============================] - 1s 8ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 90/200
75/75 [==============================] - 1s 8ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 91/200
75/75 [==============================] - 1s 8ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 92

75/75 [==============================] - 1s 9ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 164/200
75/75 [==============================] - 1s 9ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 165/200
75/75 [==============================] - 1s 9ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 166/200
75/75 [==============================] - 1s 7ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 167/200
75/75 [==============================] - 1s 7ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 168/200
75/75 [==============================] - 1s 7ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 169/200
75/75 [==============================] - 1s 8ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 170/200
75/75 [==============================] - 1s 9ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 171/200
75/75 [==============================] - 1s 11ms/step - loss: 0.1000 - accuracy: 0.0988
Epoch 172/200
75/75 [==============================] - 1s 8ms/step - loss: 0.1000 - accuracy: 0.0988
Epo

In [24]:
Standardize_oneLayer(500, 0.01, 200)

Epoch 1/200
75/75 [==============================] - 1s 7ms/step - loss: 0.6772 - accuracy: 0.7875
Epoch 2/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5535 - accuracy: 0.9421
Epoch 3/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5299 - accuracy: 0.9708
Epoch 4/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5197 - accuracy: 0.9787
Epoch 5/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5144 - accuracy: 0.9858
Epoch 6/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5114 - accuracy: 0.9862
Epoch 7/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5092 - accuracy: 0.9867
Epoch 8/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5081 - accuracy: 0.9892
Epoch 9/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5075 - accuracy: 0.9892
Epoch 10/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5071 - accuracy: 0.9900
Epoch 1

75/75 [==============================] - 1s 8ms/step - loss: 0.5047 - accuracy: 0.9925
Epoch 83/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5045 - accuracy: 0.9925
Epoch 84/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5067 - accuracy: 0.9900
Epoch 85/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5058 - accuracy: 0.9912
Epoch 86/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5057 - accuracy: 0.9917
Epoch 87/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5065 - accuracy: 0.9917
Epoch 88/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5058 - accuracy: 0.9912
Epoch 89/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5052 - accuracy: 0.9917
Epoch 90/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5045 - accuracy: 0.9925
Epoch 91/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5042 - accuracy: 0.9917
Epoch 92/200


75/75 [==============================] - 1s 7ms/step - loss: 0.5038 - accuracy: 0.9925
Epoch 164/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5038 - accuracy: 0.9925
Epoch 165/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5038 - accuracy: 0.9925
Epoch 166/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5038 - accuracy: 0.9925
Epoch 167/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5038 - accuracy: 0.9925
Epoch 168/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5038 - accuracy: 0.9925
Epoch 169/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5038 - accuracy: 0.9925
Epoch 170/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5038 - accuracy: 0.9925
Epoch 171/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5038 - accuracy: 0.9925
Epoch 172/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5038 - accuracy: 0.9925
Epoc

In [27]:
Standardize_oneLayer(500, 0.0005, 200)

Epoch 1/200
75/75 [==============================] - 1s 8ms/step - loss: 0.6764 - accuracy: 0.8037
Epoch 2/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5521 - accuracy: 0.9421
Epoch 3/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5291 - accuracy: 0.9733
Epoch 4/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5193 - accuracy: 0.9804
Epoch 5/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5140 - accuracy: 0.9842
Epoch 6/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5110 - accuracy: 0.9858
Epoch 7/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5095 - accuracy: 0.9862
Epoch 8/200
75/75 [==============================] - 1s 13ms/step - loss: 0.5087 - accuracy: 0.9867
Epoch 9/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5080 - accuracy: 0.9871
Epoch 10/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5077 - accuracy: 0.9875
Epoch

Epoch 83/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5047 - accuracy: 0.9912
Epoch 84/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5047 - accuracy: 0.9912
Epoch 85/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5047 - accuracy: 0.9912
Epoch 86/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5047 - accuracy: 0.9912
Epoch 87/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5047 - accuracy: 0.9912
Epoch 88/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5047 - accuracy: 0.9912
Epoch 89/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5047 - accuracy: 0.9912
Epoch 90/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5047 - accuracy: 0.9912
Epoch 91/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5047 - accuracy: 0.9912
Epoch 92/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5047 - accuracy: 0.9912


75/75 [==============================] - 1s 10ms/step - loss: 0.5079 - accuracy: 0.9887
Epoch 165/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5075 - accuracy: 0.9883
Epoch 166/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5069 - accuracy: 0.9896
Epoch 167/200
75/75 [==============================] - 1s 14ms/step - loss: 0.5068 - accuracy: 0.9904
Epoch 168/200
75/75 [==============================] - 1s 12ms/step - loss: 0.5064 - accuracy: 0.9900
Epoch 169/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5063 - accuracy: 0.9904
Epoch 170/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5063 - accuracy: 0.9904
Epoch 171/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5063 - accuracy: 0.9904
Epoch 172/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5063 - accuracy: 0.9904
Epoch 173/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5063 - accuracy: 0

In [28]:
#two layers standardized neural network
def Standardize_twoLayers(num_of_neurons_1, num_of_neurons_2, learning_rate_i, Epochs):
    model = keras.Sequential()
    # Add our layers
    model.add(layers.Dense(
        num_of_neurons_1, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))
    
    model.add(layers.Dense(
        num_of_neurons_2, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))

    model.add(layers.Dense(
        10, # Amount of Neurons. We want one output
        activation='sigmoid' # Use sigmoid because we want to output a binary classification
    ))

    keras.optimizers.SGD(
        learning_rate = learning_rate_i
    )
    
    model.compile(
        loss='mean_squared_error', # The loss function that is being minimized
        optimizer='adam', # Our optimization function
        metrics=['accuracy'] # Metrics are different values that you want the model to track while training
    )
    
    model.fit(
        scaled_X_train,
        scaled_Y_train,
        epochs=Epochs,  
    )
    
    model.evaluate(
        scaled_X_test,
        scaled_Y_test
    )
    predict = model.predict(scaled_X_test)
    y_test_pred = [np.argmax(i) for i in predict]
    print(tf.math.confusion_matrix(labels = test_data, predictions = y_test_pred))
    print('Test Data accuracy: ', accuracy_score(test_data, y_test_pred)*100)

In [29]:
Standardize_twoLayers(500, 100, 0.001, 200)

Epoch 1/200
75/75 [==============================] - 1s 8ms/step - loss: 0.6792 - accuracy: 0.7758
Epoch 2/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5513 - accuracy: 0.9375
Epoch 3/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5275 - accuracy: 0.9663
Epoch 4/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5169 - accuracy: 0.9792
Epoch 5/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5118 - accuracy: 0.9854
Epoch 6/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5098 - accuracy: 0.9858
Epoch 7/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5086 - accuracy: 0.9867
Epoch 8/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5080 - accuracy: 0.9871
Epoch 9/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5073 - accuracy: 0.9875
Epoch 10/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5068 - accuracy: 0.9879
Ep

75/75 [==============================] - 1s 10ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 83/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 84/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 85/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 86/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 87/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 88/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 89/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 90/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 91/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 92/200

75/75 [==============================] - 1s 9ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 164/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 165/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 166/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 167/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 168/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 169/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 170/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 171/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Epoch 172/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5037 - accuracy: 0.9942
Ep

In [30]:
#three layers standardized neural network
def Standardize_threeLayers(num_of_neurons_1, num_of_neurons_2, num_of_neurons_3, learning_rate_i, Epochs):
    model = keras.Sequential()
    # Add our layers
    model.add(layers.Dense(
        num_of_neurons_1, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))
    
    model.add(layers.Dense(
        num_of_neurons_2, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))
    
    model.add(layers.Dense(
        num_of_neurons_3, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))

    model.add(layers.Dense(
        10, # Amount of Neurons. We want one output
        activation='sigmoid' # Use sigmoid because we want to output a binary classification
    ))

    keras.optimizers.SGD(
        learning_rate = learning_rate_i
    )
    
    model.compile(
        loss='mean_squared_error', # The loss function that is being minimized
        optimizer='adam', # Our optimization function
        metrics=['accuracy'] # Metrics are different values that you want the model to track while training
    )
    
    model.fit(
        scaled_X_train,
        scaled_Y_train,
        epochs=Epochs,  
    )
    
    model.evaluate(
        scaled_X_test,
        scaled_Y_test
    )
    predict = model.predict(scaled_X_test)
    y_test_pred = [np.argmax(i) for i in predict]
    print(tf.math.confusion_matrix(labels = test_data, predictions = y_test_pred))
    print('Test Data accuracy: ', accuracy_score(test_data, y_test_pred)*100)

In [31]:
Standardize_threeLayers(500, 100, 50, 0.001, 200)

Epoch 1/200
75/75 [==============================] - 2s 8ms/step - loss: 0.7443 - accuracy: 0.6783
Epoch 2/200
75/75 [==============================] - 1s 12ms/step - loss: 0.5566 - accuracy: 0.9300
Epoch 3/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5269 - accuracy: 0.9700
Epoch 4/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5152 - accuracy: 0.9825
Epoch 5/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5103 - accuracy: 0.9862
Epoch 6/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5080 - accuracy: 0.9883
Epoch 7/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5070 - accuracy: 0.9892
Epoch 8/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5065 - accuracy: 0.9912
Epoch 9/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5057 - accuracy: 0.9908
Epoch 10/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5051 - accuracy: 0.9917
Epoch

75/75 [==============================] - 1s 9ms/step - loss: 0.5140 - accuracy: 0.9762
Epoch 83/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5127 - accuracy: 0.9800
Epoch 84/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5114 - accuracy: 0.9779
Epoch 85/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5119 - accuracy: 0.9783
Epoch 86/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5124 - accuracy: 0.9821
Epoch 87/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5099 - accuracy: 0.9833
Epoch 88/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5114 - accuracy: 0.9800
Epoch 89/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5084 - accuracy: 0.9871
Epoch 90/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5088 - accuracy: 0.9858
Epoch 91/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5086 - accuracy: 0.9887
Epoch 92/

75/75 [==============================] - 1s 10ms/step - loss: 0.5047 - accuracy: 0.9921
Epoch 164/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5047 - accuracy: 0.9921
Epoch 165/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5047 - accuracy: 0.9921
Epoch 166/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5047 - accuracy: 0.9921
Epoch 167/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5047 - accuracy: 0.9921
Epoch 168/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5047 - accuracy: 0.9921
Epoch 169/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5047 - accuracy: 0.9921
Epoch 170/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5047 - accuracy: 0.9921
Epoch 171/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5047 - accuracy: 0.9921
Epoch 172/200
75/75 [==============================] - 1s 13ms/step - loss: 0.5047 - accuracy: 0.

In [32]:
#four layers standardized neural network
def Standardize_fourLayers(num_of_neurons_1, num_of_neurons_2, num_of_neurons_3, num_of_neurons_4, learning_rate_i, Epochs):
    model = keras.Sequential()
    # Add our layers
    model.add(layers.Dense(
        num_of_neurons_1, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))
    
    model.add(layers.Dense(
        num_of_neurons_2, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))
    
    model.add(layers.Dense(
        num_of_neurons_3, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))
    
    model.add(layers.Dense(
        num_of_neurons_4, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))

    model.add(layers.Dense(
        10, # Amount of Neurons. We want one output
        activation='sigmoid' # Use sigmoid because we want to output a binary classification
    ))

    keras.optimizers.SGD(
        learning_rate = learning_rate_i
    )
    
    model.compile(
        loss='mean_squared_error', # The loss function that is being minimized
        optimizer='adam', # Our optimization function
        metrics=['accuracy'] # Metrics are different values that you want the model to track while training
    )
    
    model.fit(
        scaled_X_train,
        scaled_Y_train,
        epochs=Epochs,  
    )
    
    model.evaluate(
        scaled_X_test,
        scaled_Y_test
    )
    predict = model.predict(scaled_X_test)
    y_test_pred = [np.argmax(i) for i in predict]
    print(tf.math.confusion_matrix(labels = test_data, predictions = y_test_pred))
    print('Test Data accuracy: ', accuracy_score(test_data, y_test_pred)*100)

In [33]:
Standardize_fourLayers(500, 100, 50, 25, 0.001, 200)

Epoch 1/200
75/75 [==============================] - 1s 8ms/step - loss: 0.8101 - accuracy: 0.6108
Epoch 2/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5681 - accuracy: 0.9083
Epoch 3/200
75/75 [==============================] - 1s 12ms/step - loss: 0.5352 - accuracy: 0.9554
Epoch 4/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5221 - accuracy: 0.9712
Epoch 5/200
75/75 [==============================] - 1s 12ms/step - loss: 0.5156 - accuracy: 0.9787
Epoch 6/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5118 - accuracy: 0.9833
Epoch 7/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5109 - accuracy: 0.9821
Epoch 8/200
75/75 [==============================] - 1s 12ms/step - loss: 0.5102 - accuracy: 0.9854
Epoch 9/200
75/75 [==============================] - 1s 12ms/step - loss: 0.5075 - accuracy: 0.9896
Epoch 10/200
75/75 [==============================] - 1s 11ms/step - loss: 0.5063 - accuracy: 0.9908
Ep

75/75 [==============================] - 1s 8ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 83/200
75/75 [==============================] - 1s 9ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 84/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 85/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 86/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 87/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 88/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 89/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 90/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 91/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5032 - accuracy: 0.9954
Epoch 92/200

75/75 [==============================] - 1s 10ms/step - loss: 0.5054 - accuracy: 0.9887
Epoch 164/200
75/75 [==============================] - 1s 13ms/step - loss: 0.5054 - accuracy: 0.9887
Epoch 165/200
75/75 [==============================] - 1s 14ms/step - loss: 0.5054 - accuracy: 0.9887
Epoch 166/200
75/75 [==============================] - 1s 14ms/step - loss: 0.5054 - accuracy: 0.9887
Epoch 167/200
75/75 [==============================] - 1s 12ms/step - loss: 0.5054 - accuracy: 0.9887
Epoch 168/200
75/75 [==============================] - 1s 10ms/step - loss: 0.5053 - accuracy: 0.9887
Epoch 169/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5053 - accuracy: 0.9887
Epoch 170/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5053 - accuracy: 0.9887
Epoch 171/200
75/75 [==============================] - 1s 8ms/step - loss: 0.5053 - accuracy: 0.9887
Epoch 172/200
75/75 [==============================] - 1s 7ms/step - loss: 0.5053 - accuracy: 0.988

In [34]:
#four layers standardized neural network
def Standardize_fourLayers_batch(num_of_neurons_1, num_of_neurons_2, num_of_neurons_3, num_of_neurons_4, learning_rate_i, Epochs):
    model = keras.Sequential()
    # Add our layers
    model.add(layers.Dense(
        num_of_neurons_1, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))
    
    model.add(layers.Dense(
        num_of_neurons_2, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))
    
    model.add(layers.Dense(
        num_of_neurons_3, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))
    
    model.add(layers.Dense(
        num_of_neurons_4, # Amount of Neurons
        input_shape=(784,), # Define an input dimension because this is the first layer
        activation='relu' # Use relu activation function because all inputs are positive
    ))

    model.add(layers.Dense(
        10, # Amount of Neurons. We want one output
        activation='sigmoid' # Use sigmoid because we want to output a binary classification
    ))

    keras.optimizers.SGD(
        learning_rate = learning_rate_i
    )
    
    model.compile(
        loss='mean_squared_error', # The loss function that is being minimized
        optimizer='adam', # Our optimization function
        metrics=['accuracy'] # Metrics are different values that you want the model to track while training
    )
    
    model.fit(
        scaled_X_train,
        scaled_Y_train,
        epochs=Epochs,
        batch_size=1 
    )
    
    model.evaluate(
        scaled_X_test,
        scaled_Y_test
    )
    predict = model.predict(scaled_X_test)
    y_test_pred = [np.argmax(i) for i in predict]
    print(tf.math.confusion_matrix(labels = test_data, predictions = y_test_pred))
    print('Test Data accuracy: ', accuracy_score(test_data, y_test_pred)*100)

In [37]:
Standardize_fourLayers_batch(500, 100, 50, 25, 0.001, 2)

Epoch 1/2
2400/2400 [==============================] - 20s 8ms/step - loss: 0.6799 - accuracy: 0.7200
Epoch 2/2
7/7 [==============================] - 0s 4ms/step
tf.Tensor(
[[16  0  0  0  2  0  2  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  2 15  1  1  0  0  0  0  1]
 [ 0  0  0 17  0  3  0  0  0  0]
 [ 0  0  0  0 16  1  1  0  0  2]
 [ 2  0  0  0  0 18  0  0  0  0]
 [ 0  0  1  0  1  0 18  0  0  0]
 [ 1  0  0  0  1  0  0 16  0  2]
 [ 1  0  0  1  0  2  0  0 15  1]
 [ 1  0  0  2  2  0  0  1  0 14]], shape=(10, 10), dtype=int32)
Test Data accuracy:  82.5
